# Generated by Django 5.2.13 on 2026-04-26 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount_paise', models.BigIntegerField()),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'entry_type'], name='ledger_ledg_merchan_13a18a_idx'), models.Index(fields=['merchant', 'created_at'], name='ledger_ledg_merchan_36e37b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ledger_amount_always_positive'), models.UniqueConstraint(fields=('reference_id', 'entry_type'), name='unique_reference_entry_type')],
            },
        ),
    ]
